description: >
  See how to use our Slack notification job.
# Provide a use-case based example for using this orb.
# Everything in the `usage` section will be displayed in the orb registry.
# Comments are not retained.
usage:
  version: 2.1
  orbs:
    apollo-platform-oss-orb: apollo/internal-platform-orb@1.0.6

  jobs:
    build-and-deploy-it:
      docker:
        - image: cimg/openjdk:17.0.3
      steps:
        - run:
            command: "echo 'I would build something'"
        - run:
            command: "echo 'and I would deploy it'"
  workflows:
    use-my-orb-to-build-then-alert-slack:
      jobs:
        - build-and-deploy-it
        - apollo-platform-oss-orb/alert-slack:
            name: Alert Slack about build!
            channel: build-alerts
            emoji: ':checkered_flag:'
            notify: '*finished build* of app:my-example'
            fail: '*failed build* of app:my-example'
            requires:
              - build-and-deploy-it
            context:
              - slack-orb
            # ^^^ or whatever your context is named with your Slack token
        # If you are doing just a build notification, use the command: slack-circleci-build
        # this is for larger things like deploys
