[build]
  base    = "docs/"
  publish = "docs/public/"
  command = "gatsby build --prefix-paths && mkdir -p docs/link && mv public/* docs/link && mv docs public/ && mv public/docs/link/_redirects public"
[build.environment]
  NPM_VERSION = "6"
