version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11.1.2
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0
  nextgen-versioning: mybudget-dev/nextgen-versioning@2.0.3

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

commands:
  is-changelog-modified:
    steps:
      - run:
          name: Did you update the CHANGELOG with this branch's modifications?
          command: git diff main...HEAD --name-only | grep CHANGELOG

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

  tag-for-publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "60:6b:bb:7e:68:74:ef:e1:ad:c0:50:e3:ee:14:44:d0"
      - nextgen-versioning/git-tag:
          tag-type: ''
  apollo-checks:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - is-changelog-modified

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148,SC2001,SC1091,SC2086,SC2116,SC2046,SC2005,SC2002
      - apollo-checks:
          filters:
            tags:
              ignore: /v.*/
            branches:
              ignore: main

      # optional: Run BATS tests against your scripts
      # Publish development version(s) of the orb.
      - orb-tools/publish:
          name: "Publish Dev version"
          orb-name: apollo/internal-platform-orb
          circleci-token: CIRCLE_TOKEN
          vcs-type: << pipeline.project.type >>
          github-token: GH_BOT_KEY
          context:
            - orb-publishing
            - github-orb
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - shellcheck/check
          filters:
            tags:
              ignore: /.*/
      - tag-for-publish:   # if we are on main, tag a version number (which will then fire off a release job)
          requires:
            - "Publish Dev version"
          filters:
            tags:
              ignore: /v.*/
            branches:
              only: main
          context:
            - github-orb

  release-orb:
    jobs:
      - orb-tools/pack: # Pack orb source
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - orb-tools/publish:
          name: "Auto publish based on tag push"
          orb-name: apollo/internal-platform-orb
          circleci-token: CIRCLE_TOKEN
          vcs-type: << pipeline.project.type >>
          pub-type: production
          github-token: GH_BOT_KEY
          context:
            - orb-publishing
          requires:
            - orb-tools/pack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
