language: csharp
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet build
 - dotnet test ./Octokit.GraphQL.Core.UnitTests/Octokit.GraphQL.Core.UnitTests.csproj
 - dotnet test ./Octokit.GraphQL.UnitTests/Octokit.GraphQL.UnitTests.csproj
 - dotnet test ./Octokit.GraphQL.Core.Generation.UnitTests/Octokit.GraphQL.Core.Generation.UnitTests.csproj
 - dotnet test ./Octokit.GraphQL.IntegrationTests/Octokit.GraphQL.IntegrationTests.csproj
 addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.8