name: "Build and validate .NET generated SDK"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.x.x'

      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20.2'

      - name: Install kiota
        run: dotnet tool install --global --prerelease Microsoft.OpenApi.Kiota

      - name: Run generation
        run: time kiota generate -l csharp --ll trace -o generated/csharp/Octokit -n Octokit -d schemas/updated/api.github.com.json --co

      - name: Build post-processing
        run: go build -o post-processors/csharp/post-processor post-processors/csharp/main.go

      - name: Run post-processing
        run: post-processors/csharp/post-processor $(pwd)/generated/csharp/Octokit

      - name: Build generated and processed SDK
        run: |
          cd generated/csharp
          dotnet build
