services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 3s
      timeout: 1s
  postgraphile-server:
    build: .
    image: postgraphile-server
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGHOST=database
      - PGUSER=postgres
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    entrypoint: postgraphile --host 0.0.0.0 --port ${PORT}
    healthcheck:
      test: 'curl -f -H "content-type: application/json" -d ''{ "query": "{ __typename }" }'' http://localhost:$$PORT/graphql || exit 1'
      interval: 3s
      timeout: 1s
