services:
  deno-server:
    build: .
    image: deno-server
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    entrypoint: [deno, run, --allow-env, --allow-net, index.ts]
    healthcheck:
      test: curl -f http://localhost:$$PORT/graphql?query=%7B__typename%7D || exit 1
      interval: 3s
      timeout: 1s
