services:
  pioneer-server:
    image: pioneer-server
    build: .
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    entrypoint: .build/release/audit
    healthcheck:
      test: curl -f http://localhost:$$PORT/graphql?query=%7B__typename%7D || exit 1
      interval: 3s
      timeout: 1s
