blank_issues_enabled: false
contact_links:
  - name: Feature requests
    url: https://github.com/apollographql/apollo-client-devtools/discussions
    about: Feature requests are tracked via Discussions using the "Ideas" category.
