language: python
# sudo false implies containerized builds
#sudo: false
python:
 - "3.5"
 - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
    - pip install -r requirements.txt
script:
     - py.test tests/test_facebox.py --cov=hue --cov-report term-missing
after_success:
     - coveralls
