version: 2.1

jobs:
  build:
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - rust-target-v1-test-{{ checksum "Cargo.toml" }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - rust-target-v1-test-{{ checksum "Cargo.toml" }}-{{ .Branch }}
            - rust-target-v1-test-{{ checksum "Cargo.toml" }}
      - run: cargo build
      - run: cargo test
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all --tests -- -D warnings
      - save_cache:
          key: rust-target-v1-test-{{ checksum "Cargo.toml" }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - target/
