apiVersion: v1
kind: Service
metadata:
  name: products-preview
spec:
  selector:
    app: subgraph-products
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: users-preview
spec:
  selector:
    app: subgraph-users
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-preview
spec:
  selector:
    app: subgraph-inventory
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
