services:
  hotchocolate-server:
    image: hotchocolate-server
    build: .
    environment:
      - DOTNET_URLS=http://+:${PORT}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    entrypoint: dotnet run
    healthcheck:
      test: curl -f http://localhost:$$PORT/graphql?query=%7B__typename%7D || exit 1
      interval: 3s
      timeout: 1s
