trigger: none

pr:
  branches:
    include:
    - master

variables:
  DDEV_COLOR: 1

resources:
  repositories:
    - repository: integrations-core
      type: github
      name: Datadog/integrations-core
      ref: master
      endpoint: DataDog

jobs:
- template: '.azure-pipelines/templates/test-single-linux.yml@integrations-core'
  parameters:
    job_name: Changed
    display: Linux
    validate: true
    repo: 'extras'

- template: '.azure-pipelines/templates/test-single-windows.yml@integrations-core'
  parameters:
    job_name: Changed
    check: '--changed none_yet'
    display: Windows
    repo: 'extras'
