# This compose runs HBase in pseudo-dist mode with independent Hadoop and Zookeeper.
# NOTE: The file is borrowed from https://github.com/mcapitanio/docker-hbase
version: "2"

services:

    zookeeper:
        extends:
            file: zookeeper.yml
            service: zookeeper

    hadoop:
        extends:
            file: hadoop.yml
            service: hadoop
        links:
            - zookeeper

    hbase:
        image: mcapitanio/hbase:latest
        networks:
            - hadoop
        volumes:
            - hbase_logs:/opt/hbase/logs
            - hbase_conf:/opt/hbase/conf
        volumes_from:
            - hadoop
        links:
            - hadoop
            - zookeeper
        environment:
          HBASE_MASTER_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=10101 -Dcom.sun.management.jmxremote.rmi.port=10101 -Djava.rmi.server.hostname=127.0.0.1"
          HBASE_REGIONSERVER_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=10102 -Dcom.sun.management.jmxremote.rmi.port=10102 -Djava.rmi.server.hostname=127.0.0.1"
        expose:
          - "10101"
          - "10102"
        ports:
            - "10101:10101"
            - "10102:10102"
            - "8080:8080"
            - "8085:8085"
            - "9090:9090"
            - "9095:9095"
            - "60000:60000"
            - "60010:60010"
            - "60020:60020"
            - "60030:60030"

volumes:
    hadoop_conf:
    hadoop_hdfs:
    hadoop_logs:
    hbase_conf:
    hbase_logs:
    zookeeper_conf:
    zookeeper_logs:
    zookeeper_data:

networks:
    hadoop:
        driver: bridge
