version: "2"

services:

    zookeeper:
        image: mcapitanio/zookeeper
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        networks:
            - hadoop
        volumes:
            - zookeeper_data:/zookeeper/data
            - zookeeper_logs:/zookeeper/logs
            - zookeeper_conf:/opt/zookeeper/conf

networks:
    hadoop:
        driver: bridge
