apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../stage
- ../bluegreen

# make deployment template
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: products
  spec:
    replicas: 0
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: inventory
  spec:
    replicas: 0
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: users
  spec:
    replicas: 0
